#!/bin/bash
set -euo pipefail
usage() {
    cat <<EOF
Usage: $0 [OPTIONS]

Options:
  --try                    Run the script in try mode. (optional, default: false)
  --version IMAGE_VERSION  Specify the image version. Like '1.0.0'. (required if not in try mode)
  --verbose                Enable verbose output. (optional, default: false)
  -h, --help               Show this help message.
EOF
}





if [[ $(getopt --test > /dev/null 2>&1; echo $?) -ne 4 ]]; then
    echo "error: This script requires GNU getopt. Please install it and try again." >&2
    echo "macOS users can install GNU getopt using Homebrew: 'brew install gnu-getopt'" >&2
    exit 1
fi

PARSED_ARGS=$(getopt --options 'h' --longoptions 'help,try,version:,verbose' -- "$@")
if [[ $? -ne 0 ]]; then
    echo "error: Failed to parse arguments." >&2
    usage >&2
    exit 1
fi
eval set -- "$PARSED_ARGS"
unset PARSED_ARGS

TRY_RUN='false'
VERBOSE_RUN='false'
IMAGE_VERSION=''
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --try)
            TRY_RUN='true'
            shift
            ;;
        --version)
            IMAGE_VERSION="$2"
            shift 2
            ;;
        --verbose)
            VERBOSE_RUN='true'
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            usage >&2
            exit 1
            ;;
    esac
done
readonly TRY_RUN
readonly VERBOSE_RUN


if [[ -z "$IMAGE_VERSION" ]]; then
    if $TRY_RUN; then
        echo "warning: Running in try mode. The image version filled by '0.0.0' if not specified." >&2
        IMAGE_VERSION='0.0.0'
    else
        echo "error: --version IMAGE_VERSION is required." >&2
        usage >&2
        exit 1
    fi
fi
readonly IMAGE_VERSION

get_image_vcs_rev() {
    local local_head=$(git rev-parse HEAD)
    if [ -z "$local_head" ]; then
        echo "error: Unable to determine the local HEAD." >&2
        return 1
    fi

    if $TRY_RUN; then
        echo "warning: Running in try mode. Skipping VCS revision check." >&2
        return 0
    fi

    local current_branch=$(git rev-parse --abbrev-ref HEAD)
    if [ -z "$current_branch" ]; then
        echo "error: Unable to determine the current branch." >&2
        return 1
    fi

    local remote_head=$(git ls-remote origin "$current_branch" | awk '{print $1}')
    if [ $? -ne 0 ]; then
        echo "error: Unable to determine the remote HEAD." >&2
        return 1
    fi

    if [ "$local_head" != "$remote_head" ]; then
        echo "error: Local HEAD ($local_head) does not match remote HEAD ($remote_head) on branch '$current_branch'." >&2
        return 1
    fi

    if ! git diff-index --quiet HEAD --; then
        echo "error: There are uncommitted changes in the repository." >&2
        return 1
    fi

    echo "$local_head"
}

IMAGE_VCS_REV=$(get_image_vcs_rev) || exit 1
readonly IMAGE_VCS_REV

get_host_arch() {
    local RAW_ARCH="$1"

    case "$RAW_ARCH" in
        x86_64|amd64)
            echo "amd64"
            ;;
        aarch64|arm64)
            echo "arm64"
            ;;
        *)
            echo "error: Unsupported host architecture: $RAW_ARCH" >&2
            ;;
    esac
}

HOST_ARCH=$(get_host_arch "$(uname -m)")

TAG_PREFIX='try0-'
if $TRY_RUN; then
    TAG_PREFIX='dont-push-'
    echo "warning: Running in try mode. The image tag is prefixed with '$TAG_PREFIX'." >&2
fi
BUILD_PROGRESS='tty'
if $VERBOSE_RUN; then
    BUILD_PROGRESS='plain'
fi

TARGET_ARCHS=("arm-linux-gnueabihf" "aarch64-linux-gnu")
for TARGET_ARCH in "${TARGET_ARCHS[@]}"; do
    IMAGE_BUILT_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    if $TRY_RUN; then
        IMAGE_BUILT_AT='1970-01-01T00:00:00Z'
        echo "warning: Running in try mode. The image build time is fixed to '$IMAGE_BUILT_AT'." >&2
    fi
    docker buildx build . \
      --platform linux/${HOST_ARCH} --load \
      --build-arg TARGET_ARCH=$TARGET_ARCH \
      --build-arg IMAGE_VERSION="$IMAGE_VERSION" \
      --build-arg IMAGE_VCS_REV="$IMAGE_VCS_REV" \
      --build-arg IMAGE_BUILT_AT="$IMAGE_BUILT_AT" \
      -t "cross-rpi:${TAG_PREFIX}${TARGET_ARCH}-${HOST_ARCH}" \
      --progress=$BUILD_PROGRESS
    if $TRY_RUN && $VERBOSE_RUN; then
        docker inspect "cross-rpi:${TAG_PREFIX}${TARGET_ARCH}-${HOST_ARCH}"
    fi
done

for TARGET_ARCH in "${TARGET_ARCHS[@]}"; do
    echo "Image 'cross-rpi:${TAG_PREFIX}${TARGET_ARCH}-${HOST_ARCH}' built successfully."
done

#
# after building, push the image to the registry
#
# docker login
# docker tag cross-rpi:${TARGET_ARCH}-amd64 idein/cross-rpi:${TARGET_ARCH}-amd64
# docker tag cross-rpi:${TARGET_ARCH}-arm64 idein/cross-rpi:${TARGET_ARCH}-arm64
# docker push idein/cross-rpi:${TARGET_ARCH}-amd64
# docker push idein/cross-rpi:${TARGET_ARCH}-arm64
# docker manifest create idein/cross-rpi:${TARGET_ARCH} \
#   --amend idein/cross-rpi:${TARGET_ARCH}-amd64 \
#   --amend idein/cross-rpi:${TARGET_ARCH}-arm64
# docker manifest push idein/cross-rpi:${TARGET_ARCH}
#
